name: guardiao_de_senhas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  file_picker: ^8.1.2
  path_provider: ^2.1.1
  path: ^1.8.3
  intl: ^0.18.1
  provider: ^6.1.5
  local_auth: ^2.1.4
  crypto: ^3.0.6
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider_windows: ^2.2.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:

  # pasta de imagens logo
    - 'assets/logo/guardiao.png'
    - 'assets/logo/guardiao_transparente.png'

  # pasta de imagens animation
    - 'assets/animation/guardiao_apresentacao_transparente.png' # Tela de apresentação
    - 'assets/animation/guardiao_biometria_transparente.png' # Tela de biometria
    - 'assets/animation/guardiao_final_transparente.png' # Tela final
    - 'assets/Animation/guardiao_nome_transparente.png' # Tela de nome
    - 'assets/animation/guardiao_PerguntaSeguranca_transparente.png' # Tela de pergunta de segurança
    - 'assets/Animation/guardiao_senhaMestra_transparente.png' # Tela de senha mestra