name: guardiao_de_senhas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  local_auth: ^2.1.4
  crypto: ^3.0.6
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - 'assets/backgrounds/bg1.png'
  #  - 'assets/backgrounds/bg2.png'
  #  - 'assets/backgrounds/bg3.png'
  #  - 'assets/backgrounds/bg4.png'
  #  - 'assets/backgrounds/bg5.png'