name: guardiao_de_senhas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  local_auth: ^2.1.4
  crypto: ^3.0.6
  provider: ^6.1.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  # pasta de imagens background
    - 'assets/backgrounds/bg1.png'
    - 'assets/backgrounds/bg2.png'
    - 'assets/backgrounds/bg3.png'
    - 'assets/backgrounds/bg4.png'
    - 'assets/backgrounds/bg5.png'

  # pasta de imagens logo
    - 'assets/logo/guardiao.png'
    - 'assets/logo/guardiao_transparente.png'

  # pasta de imagens animação
    - 'assets/animacao/guardiao_apesentacao.png'
    - 'assets/animacao/guardiao_nome.png'
    - 'assets/animacao/guardiao_senhaMestra.png'
    - 'assets/animacao/guardiao_PerguntaSeguranca.png'
    - 'assets/animacao/guardiao_SenhaMestra.png'
    - 'assets/animacao/guardiao_biometria.png'
    - 'assets/animacao/guardiao_final.png'